name: Daily Telegram Bot

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    name: Deployment 1
    
    env:
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Cookies Rev
        run: |
          echo "Decoding YouTube cookies for verification..."
          echo $YOUTUBE_COOKIES | base64 -d || echo "Invalid base64 input"
          echo "Cookie decoding test completed."

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install FFmpeg for audio processing
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Run Klavir Bot
        run: |
          python test_script.py
