name: Scheduled Music Sender

on:
  #schedule:
    #- cron: '0 8-22/1,30 6-22/1 * * *' # Every 1.5 hours from 8:00 to 22:30 UTC+3:30 (Tehran)
    #- cron: '0 8,9,10,11,12,13,14,15,16,17,18,19,20,21,22 * * *' # fallback for every hour
  workflow_dispatch:

jobs:
  send_music:
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      CLOUDFARE_WORKER_URL: ${{ secrets.CLOUDFARE_WORKER_URL }}
      GH_PAT: ${{ secrets.GH_PAT }}
      KLAVIR_TOKEN: ${{ secrets.KLAVIR_TOKEN }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
      YOUTUBE_PASSWORD: ${{ secrets.YOUTUBE_PASSWORD }}
      YOUTUBE_USERNAME: ${{ secrets.YOUTUBE_USERNAME }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      CITY: ${{ vars.CITY }}
      COOKIES_FILE_PATH: ${{ vars.COOKIES_FILE_PATH }}
      REGION: ${{ vars.REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pull API keys YAML
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -o service_keys.yaml \
          https://raw.githubusercontent.com/Zudiaq/youtube-mp3-apis/main/youtube-mp3-api-stats.yaml
      - name: Run send_music.py
        run: python send_music.py
