name: Klavir Workflow

on:
  workflow_dispatch:  

jobs:
  run-klavir:
    name: Run Klavir Application
    runs-on: ubuntu-latest
    environment: Deployment 1
    
    env:
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      SPOTDL_DOWNLOAD_DIR: /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Create download directory
        run: mkdir -p /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download

      - name: Test YouTube cookies
        run: |
          echo ${{ secrets.YOUTUBE_COOKIES }} | base64 --decode > /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download/cookies.txt
          yt-dlp --cookies /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download/cookies.txt --skip-download --get-title "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
          if [ $? -ne 0 ]; then
            echo "Cookies expired, updating..."
            base64 < ~/.cache/yt-dlp/youtube/cookies.txt | gh secret set "YOUTUBE_COOKIES" --repo ${{ github.repository }} --token ${{ secrets.GH_PAT }}
            echo ${{ secrets.YOUTUBE_COOKIES }} | base64 --decode > /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download/cookies.txt
            yt-dlp --cookies /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download/cookies.txt --skip-download --get-title "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
            if [ $? -ne 0 ]; then
              echo "Failed to update cookies."
              exit 1
            fi
          fi

      - name: Download YouTube content
        run: |
          yt-dlp --default-search "ytsearch" --cookies /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download/cookies.txt --output "/home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download/%(title)s.%(ext)s" "<URL>"
          if [ $? -ne 0 ]; then
            echo "Cookies expired, updating..."
            base64 < ~/.cache/yt-dlp/youtube/cookies.txt | gh secret set "YOUTUBE_COOKIES" --repo ${{ github.repository }} --token ${{ secrets.GH_PAT }}
            exit 1
          fi

      - name: Update YouTube cookies for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: '[Convert]::ToBase64String([IO.File]::ReadAllBytes("$env:USERPROFILE\.cache\yt-dlp\youtube\cookies.txt")) | gh secret set "YOUTUBE_COOKIES"'
        env:
          cookies_secret_name: ${{ secrets.YOUTUBE_COOKIES }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GH_REPO: ${{ github.repository }}
      
      - name: Create download directory
        run: mkdir -p /home/runner/work/klavir-alpha/klavir-alpha/temp/spotdl_download
      
      - name: Send Quote
        run: python send_quote.py
      
      - name: Send Weather
        run: python send_weather.py
      
      - name: Send Music Recommendation
        run: python send_music.py
      
      - name: Update yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies/update@v3
        with:
          cookies_secret_name: YOUTUBE_COOKIES
          token: ${{ secrets.GH_PAT }}
