name: Test Music Sender

on:
  workflow_dispatch:

jobs:
  send_music:
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      SPOTDL_DOWNLOAD_DIR: ${{ github.workspace }}/temp/spotdl_download
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup proxy providers
        run: |
          # Create necessary directories if they don't exist
          mkdir -p yt-dlp-proxy/proxy_providers
          # Copy proxy provider files to ensure they're available
          # Copy proxy provider files only if they don't already exist
          find yt-dlp-proxy/proxy_providers -type f -exec cp -n {} yt-dlp-proxy/proxy_providers/ \;
          # Ensure proxy.json exists (will be created if not)
          touch proxy.json
      - name: Run send_music.py
        run: |
          mkdir -p yt-dlp-proxy/proxy_providers
          python send_music.py
