name: Test Script Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      SPOTDL_DOWNLOAD_DIR: ${{ github.workspace }}/temp/spotdl_download
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test script
      run: |
        python test_script.py
