name: Scheduled Music Sender

on:
  workflow_dispatch:

jobs:
  send_music:
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      GH_PAT: ${{ secrets.GH_PAT }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pull API keys YAML
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -o service_keys.yaml \
          https://raw.githubusercontent.com/Zudiaq/youtube-mp3-apis/main/youtube-mp3-api-stats.yaml
      - name: Run send_music.py
        run: python send_music.py
