name: Scheduled Tasks

on:
  schedule:
    - cron: '30 8 * * *' # Run at 8:30 AM daily
    - cron: '30 9-23/1 * * *' # Update weather every hour from 9:30 AM to 11:30 PM
    - cron: '30 8-23/2 * * *' # Send music every 1.5 hours starting at 8:30 AM

jobs:
  morning_tasks:
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send morning weather update
        run: python send_weather.py

      - name: Send daily quote
        run: python send_quote.py

  update_weather:
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update weather message
        run: python send_weather.py update

  send_music:
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      GH_PAT: ${{ secrets.GH_PAT }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send music recommendation
        run: python send_music.py
