name: Scheduled Workflow

on:
    workflow_dispatch:
#  schedule:
#   - cron: '30 8 * * *' # Run at 8:30 AM daily
#    - cron: '30 9-23/1 * * *' # Update weather every hour from 9:30 AM to 11:30 PM
#    - cron: '30 8-23/2 * * *' # Send music every 1.5 hours starting at 8:30 AM

jobs:
  morning_tasks:
    if: github.event.schedule == '30 8 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send morning weather update
        run: python send_weather.py

      - name: Send daily quote
        run: python send_quote.py

  update_weather:
    if: github.event.schedule == '30 9-23/1 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update weather message
        run: python update_weather.py

  send_music:
    if: github.event.schedule == '30 8-23/2 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send music recommendation
        run: python send_music.py
