name: Panel

on:
  workflow_dispatch: # Allow manual start
  schedule:
    - cron: "0 */6 * * *" # Restart every 6 hours

jobs:

  panel:
    runs-on: ubuntu-latest

    concurrency: # Prevent overlapping workflows
      group: panel-bot
      cancel-in-progress: true

    environment: Deployment 1
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      GH_PAT: ${{ secrets.GH_PAT }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install python-telegram-bot pyyaml nest_asyncio

      - name: Run panel
        run: |
          echo "Starting the bot..."
          python panel.py
