name: Scheduled Tasks

on:
  schedule:
    - cron: '0 5 * * *'  # 8:30 AM (Tehran time - 5:00 AM UTC)
    - cron: '30 5 * * *'  # 9:00 AM (Tehran time - 5:30 AM UTC)
    - cron: '0 7 * * *'   # 10:30 AM (Tehran time - 7:00 AM UTC)
    - cron: '30 8 * * *'  # 12:00 PM (Tehran time - 8:30 AM UTC)
    - cron: '0 10 * * *'  # 1:30 PM (Tehran time - 10:00 AM UTC)
    - cron: '30 11 * * *' # 3:00 PM (Tehran time - 11:30 AM UTC)
    - cron: '0 13 * * *'  # 4:30 PM (Tehran time - 1:00 PM UTC)
    - cron: '30 14 * * *' # 6:00 PM (Tehran time - 2:30 PM UTC)
    - cron: '0 16 * * *'  # 7:30 PM (Tehran time - 4:00 PM UTC)
    - cron: '30 17 * * *' # 9:00 PM (Tehran time - 5:30 PM UTC)
    - cron: '0 19 * * *'  # 10:30 PM (Tehran time - 7:00 PM UTC)
    - cron: '30 19 * * *'   # 11:00 AM (Tehran time - 7:30 PM UTC) - Keeping the nightly quote

jobs:
  morning_weather_quote:
    name: Sending Morning Weather Stats and Daily Quote
    if: startsWith(github.event.schedule, '0 5')  # Run only at 8:30 AM (Tehran time)
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send morning weather update
        run: python send_weather.py
        continue-on-error: true

      - name: Notify admin on failure
        if: failure()
        run: python notify_admin.py "Morning weather update failed."

      - name: Send daily quote
        run: python send_quote.py
        if: success()

  music_and_weather_updates:
    name: Sending Music and Updating Weather
    if: startsWith(github.event.schedule, '30 5') || startsWith(github.event.schedule, '0 7') || startsWith(github.event.schedule, '30 8') || startsWith(github.event.schedule, '0 10') || startsWith(github.event.schedule, '30 11') || startsWith(github.event.schedule, '0 13') || startsWith(github.event.schedule, '30 14') || startsWith(github.event.schedule, '0 16') || startsWith(github.event.schedule, '30 17') || startsWith(github.event.schedule, '0 19')
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
      API_SELECTION: ${{ vars.API_SELECTION }}
      GH_PAT: ${{ secrets.GH_PAT }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
      CITY: ${{ vars.CITY }}
      REGION: ${{ vars.REGION }}
      WEATHER_MESSAGE_ID: ${{ vars.WEATHER_MESSAGE_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send music recommendation
        run: python send_music.py
        continue-on-error: true

      - name: Notify admin on failure
        if: failure()
        run: python notify_admin.py "Music recommendation failed."

      - name: Update weather message
        run: python update_weather.py update
        continue-on-error: true

      - name: Notify admin on failure
        if: failure()
        run: python notify_admin.py "Weather update failed."

  nightly_quote:
    name: Sending Nightly Quote
    if: startsWith(github.event.schedule, '30 19')  # Run only at 11:00 PM (Tehran time)
    runs-on: ubuntu-latest
    environment: Deployment 1
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GH_PAT: ${{ secrets.GH_PAT }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      DEBUG_MODE: ${{ vars.DEBUG_MODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send nightly quote
        run: python send_quote.py --night
        continue-on-error: true

      - name: Notify admin on failure
        if: failure()
        run: python notify_admin.py "Nightly quote failed."
