name: Manual Test Run

on:
  workflow_dispatch:

jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test script
        env:
          TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
          OPENWEATHERMAP_API_KEY: ${{ env.OPENWEATHERMAP_API_KEY }}
          LASTFM_API_KEY: ${{ env.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ env.LASTFM_API_SECRET }}
          SPOTIFY_CLIENT_ID: ${{ env.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ env.SPOTIFY_CLIENT_SECRET }}
        run: |
          python test_script.py
