name: Manual Test Run

on:
  workflow_dispatch:

jobs:
  test-bot:
    runs-on: ubuntu-latest
    environment: APIs  
    env:
      TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ vars.OPENWEATHERMAP_API_KEY }}
      LASTFM_API_KEY: ${{ vars.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ vars.LASTFM_API_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ vars.SPotify_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ vars.SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate environment variables
        run: |
          required_vars=(
            TELEGRAM_BOT_TOKEN
            TELEGRAM_CHAT_ID
            OPENWEATHERMAP_API_KEY
            LASTFM_API_KEY
            LASTFM_API_SECRET
            SPOTIFY_CLIENT_ID
            SPOTIFY_CLIENT_SECRET
          )
          missing_vars=()
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              missing_vars+=("$var")
            fi
          done
          if [ ${#missing_vars[@]} -ne 0 ]; then
            echo "Error: The following required variables are not set: ${missing_vars[*]}"
            exit 1
          fi

      - name: Run test script
        run: |
          python test_script.py || exit 0
