name: Manual Test Run

on:
  workflow_dispatch:

env:
  CITY: ${{ vars.CITY }}
  REGION: ${{ vars.REGION }}
  API_SELECTION: ${{ vars.API_SELECTION }}

jobs:
  test-bot:
    runs-on: ubuntu-latest
    environment: Deployment 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install you-get and ffmpeg
        run: |
          pip install you-get
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Run test script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          python test_script.py || exit 1
