name: Manual Test Run

on:
  workflow_dispatch:

env:
  CITY: ${{ vars.CITY }}
  REGION: ${{ vars.REGION }}
  API_SELECTION: ${{ vars.API_SELECTION }}

jobs:
  test-bot:
    runs-on: ubuntu-latest
    environment: Deployment 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Clone private repository
        run: |
          git clone https://${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/Zudiaq/Cookies.git private_repo
      - name: List contents of private_repo
        run: ls -R private_repo
      - name: Use Cookies.txt
        run: |
          cp private_repo/Cookies.txt Cookies.txt
          echo "COOKIES_FILE_PATH=$(pwd)/Cookies.txt" >> $GITHUB_ENV
      - name: Verify cookies.txt
        run: |
          echo "Cookies file path: $(pwd)/Cookies.txt"
          cat Cookies.txt || echo "cookies.txt is missing or empty"
      - name: Refresh Cookies if Needed
        run: |
          python -c "from youtube_downloader import trigger_refresh_cookies_workflow; trigger_refresh_cookies_workflow()"
      - name: Run test script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          python test_script.py || exit 1
      - name: Cleanup Cookies.txt
        if: always()
        run: rm -f Cookies.txt
