name: Manual Test Run

on:
  workflow_dispatch:

jobs:
  test-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ vars.OPENWEATHERMAP_API_KEY }}
      LASTFM_API_KEY: ${{ vars.LASTFM_API_KEY }}
      LASTFM_API_SECRET: ${{ vars.LASTFM_API_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ vars.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ vars.SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test script
        run: |
          python test_script.py || exit 0
