name: Weather and Quote Sender

on:
  schedule:
    - cron: '30 6 * * *' # 9:30 AM Tehran time (UTC+3:30)
  workflow_dispatch:

jobs:
  send_weather_and_quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run send_weather.py
        run: python send_weather.py
      - name: Run send_quote.py
        run: python send_quote.py